language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pylint triangle.py
  - pylint test_triangle.py
  - coverage run -m unittest test_triangle

after_success:
  - bash <(curl -s https://codecov.io/bash)
