language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  # - pylint triangle.py || exit 0
  # - pylint test_triangle.py || exit 0
  - coverage run -m unittest test_triangle

after_success:
  - bash <(curl -s https://codecov.io/bash)
