language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pylint Triangle.py || exit 0
  - pylint TestTriangle.py || exit 0
  - coverage run -m unittest TestTriangle

after_success:
  - bash <(curl -s https://codecov.io/bash)
